DROP TABLE CATEGORY ;


INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('Light','Sandwich','sand.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('Hearty','Main Dishes','dishes.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('Starters','Appetizers ','app.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('Extras','Side Dishes ','side.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('Sweets','Desserts','sweet.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('Cold','Cold Drinks ','cold.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('warm','Hot Drinks','hot.svg');
INSERT INTO CATEGORY (HIGHLIGHT,NAME,ICON) VALUES ('All','ALL','main.svg');


